repos:
  - repo: local
    hooks:
      - id: check
        name: Check Code Issues
        entry: sh -c "source .venv/bin/activate &&ruff check"
        args: [ -q ]
        language: python
        files: .*\.py$
  - repo: local
    hooks:
      - id: format
        name: Format Code
        entry: sh -c "source .venv/bin/activate && ruff format"
        language: python
        files: .*\.py$